### PR TITLE
Fix Issues in Table with SST enabled

### PR DESCRIPTION
**Pull request by samisgod**
ignore changes in dist folder

changes in vsTable.vue will fix this issue

### CODE REVIEW

**Comment by jd-solanki** [comment]
Hey, @samisgod We are really sorry. We didn't check this repo. We will review this and merge it into this forked repo.
Thanks for your contribution. :pray:

**Comment by jd-solanki** [comment]
Hi @samisgod please don't create a build version. It can conflict with the existing code. Could you please resolve this issue or do you want use to just update your code in our repo and close this PR?

Awaiting your response. Thanks so much for your contribution. 🙌

**Comment by jd-solanki** [comment]
Hi @samisgod,

We have used your changes for this forked repo in our [branch](https://github.com/jd-0001/vuesax/tree/table-fix-experimental).

Please take a pull from that branch and let us know if it's fine for you. If this works we will merge it in master. :pray: 

Thanks so much for your contribution.

**Comment by samisgod** [comment]
yes, the server side pagination works fine now, thanks for this fix.











在 2020-08-13 23:51:48，"JD" <notifications@github.com> 写道：

Hi @samisgod,

We have used your changes for this forked repo in our branch.

Please take a pull from that branch and let us know if it's fine for you. If this works we will merge it in master.

Thanks so much for your contribution.

**Pull request closed without merging**
